import type { Metadata } from 'next'
import React from 'react'
import '@/app/_styles/index.scss'

export const metadata: Metadata = {
  title: 'next start project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
